[[language]]
auto-format = true
formatter.command = "alejandra"
language-servers = ["nixd"]
name = "nix"

[[language]]
auto-format = true
file-types = ["sh", "bash", "dash", "ksh", "mksh"]
formatter = { command = "shfmt", args = ["-i", "4"] }
language-servers = [ "bash-language-server" ]
name = "bash"

[[language]]
auto-format = true
file-types = ["md", "markdown", "mdx"]
formatter = { command = "mdformat", args = ["-"] }
name = "markdown"

[language-server.bash-language-server]
args = ["start"]
command = "bash-language-server"