name: build-deploy-nixos-hosts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
jobs:
  build-and-deploy-mauville:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build mauville
        run: nix build --accept-flake-config .#nixosConfigurations.mauville.config.system.build.toplevel
      - name: Configure SSH Credentials
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printenv SSH_KEY > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printenv SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          sudo cp -r $HOME/.ssh /root
      - name: Deploy mauville
        run: nix run nixpkgs#nixos-rebuild -- switch --flake .#mauville --target-host root@mauville --build-host localhost
  build-and-deploy-slateport:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build slateport
        run: nix build --accept-flake-config .#nixosConfigurations.slateport.config.system.build.toplevel
      - name: Configure SSH Credentials
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printenv SSH_KEY > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printenv SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          sudo cp -r $HOME/.ssh /root
      - name: Deploy slateport
        run: nix run nixpkgs#nixos-rebuild -- switch --flake .#slateport --target-host root@slateport --build-host localhost
