name: "flake: format check"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20

      - name: Check if flake complies with default style
        run: nix fmt -- -c .
