name: "check-nix-flake"
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - '_img/**'
  workflow_dispatch:
jobs:
  check-fmt:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check formatting
        run: nix fmt -- -c .
  check-eval:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake evaluation
        run: nix flake check
