name: "update-flake-inputs"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "flake: update inputs"
          pr-assignees: alyraffauf
          pr-reviewers: alyraffauf
          pr-labels: |
            dependencies
            automated