name: "flake-update"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  inputs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Setup Git
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email  "github-actions[bot]@users.noreply.github.com"
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update fetchGit repos
        run: |
          nix run nixpkgs#update-nix-fetchgit -- homeManagerModules/desktop/default.nix
          nix run nixpkgs#update-nix-fetchgit -- homes/aly/firefox/default.nix
          nix run nixpkgs#update-nix-fetchgit -- homes/aly/mail/default.nix
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.FLAKE_UPDATE_PAT }}
          pr-title: "flake: update inputs"
          pr-assignees: alyraffauf
          pr-labels: |
            dependencies
            automated