name: "git-mirror"
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "sync gitlab mirror"
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'https://gitlab.com/alyraffauf/nixcfg.git'
          GIT_USERNAME: alyraffauf
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
