name: mirror-gitlab
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  mirror-gitlab:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare "${{ github.server_url }}/${{ github.repository }}.git" .
      - run: git push --mirror "https://x:$GITLAB_PASSWORD@gitlab.com/alyraffauf/nixcfg.git"
        env:
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
