name: mirror-gitlab
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  mirror-gitlab:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare "https://github.com/alyraffauf/nixcfg.git" .
      - run: git push --mirror "https://x:$GITLAB_PASSWORD@gitlab.com/alyraffauf/nixcfg.git"
        env:
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}