name: "nix-build"
on:
  push:
    paths-ignore:
      - '.github/**'
      - '_img/**'
  workflow_dispatch:
jobs:
  default-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build default package
        run: nix build --accept-flake-config .#packages.x86_64-linux.default
  fallarbor-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build fallarbor
        run: nix build --accept-flake-config .#nixosConfigurations.fallarbor.config.system.build.toplevel
  lavaridge-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build lavaridge
        run: nix build --accept-flake-config .#nixosConfigurations.lavaridge.config.system.build.toplevel
  mauville-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build mauville
        run: nix build --accept-flake-config .#nixosConfigurations.mauville.config.system.build.toplevel
  petalburg-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build petalburg
        run: nix build --accept-flake-config .#nixosConfigurations.petalburg.config.system.build.toplevel
  rustboro-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build rustboro
        run: nix build --accept-flake-config .#nixosConfigurations.rustboro.config.system.build.toplevel